language: csharp
solution: Kip.sln
mono:
  - latest
  - 3.10.0
install:
  - nuget restore Kip.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Kip.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Kip.Tests/bin/Release/Kip.Tests.dll
